### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by sroettgermann** [DWilches/Vrpn2Unity#2]
Hi Daniel!

I'm trying to read the VRPN timestamp. 
Can you help me with this? I did not know how to get it with your code examples.

Hopefully you can help me with this.

**Comment by dwilches** [comment]
Hello,

I didn't consider exposing the timestamps when I first made this library, but the change is easy to make. I have done a sample implementation of the change in the new branch [feature_enable_timestamps](https://github.com/DWilches/Vrpn2Unity/tree/feature_enable_timestamps) but I don't have the necessary software to compile it now (Visual Studio 2013).

Please note I stopped maintaining this project as Unity stopped producing the 32-bit version of their editor ([check the new here](https://blogs.unity3d.com/2016/11/15/end-of-support-for-32-bit-editor-for-windows/)) and Vrpn only works as a 32-bit lib/dll.

All the best!

**Comment by sroettgermann** [comment]
Hi! 

Thanks for your answer. 
So what exactly do I have to compile with VS2013 (I have it installed) to make it to work. That would help me a lot.

Thanks for the hint regarding Unity. But currently I have no other choice. 👎 

regards
Seb

**Comment by dwilches** [comment]
Open the Vrpn2Unity_DLL solution in VS2013 and compile it. It will generate a DLL you need to put into your Unity project, in the folder Plugins.

Also, I updated the 2 files from the `Scripts`project, you need to update those too: `SampleMouseBehaviour.cs` and `VRPNController.cs`

**Comment by sroettgermann** [comment]
Thank you very much. I will give it a try.
